services:
  - type: web
    name: erp-api
    env: python
    buildCommand: ""
    startCommand: uvicorn main:app --host 0.0.0.0 --port 10000
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: erp-db
          property: connectionString
      - key: SECRET_KEY
        value: your-secret-key-here

databases:
  - name: erp-db
    plan: free
